name: FunTalismans
version: '1.0.0'
main: ft.keraune.funtalismans.FunTalismans
api-version: '1.21'
author: Keraune
depend: [NBTAPI]

commands:
  talisman:
    description: Talisman command
    usage: /talisman
    aliases: [tali, talismans, ftalismans, ft]

